/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PipesGUI;

import TypeFive;
import TypeFour;
import TypeOne;
import TypeThree;
import TypeTwo;

/**
 *
 * @author James
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        oneColour = new javax.swing.JRadioButton();
        twoColours = new javax.swing.JRadioButton();
        noColours = new javax.swing.JRadioButton();
        insulationYes = new javax.swing.JRadioButton();
        insulationNo = new javax.swing.JRadioButton();
        reinforcementYes = new javax.swing.JRadioButton();
        reinforcementNo = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        chemResistanceYes = new javax.swing.JRadioButton();
        chemResistanceNo = new javax.swing.JRadioButton();
        txtPipeSize = new javax.swing.JTextField();
        txtPipeDiameter = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        butCalculate = new javax.swing.JButton();
        butAdd = new javax.swing.JButton();
        pipeGrade1 = new javax.swing.JRadioButton();
        pipeGrade2 = new javax.swing.JRadioButton();
        pipeGrade3 = new javax.swing.JRadioButton();
        pipeGrade4 = new javax.swing.JRadioButton();
        pipeGrade5 = new javax.swing.JRadioButton();
        butExit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPipeCost = new javax.swing.JTextField();
        txtPipeType = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsole = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pipes R 'Us");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pipes R 'Us Order System"));

        jLabel1.setText("Enter Pipe Size");

        jLabel2.setText("Enter Pipe Diameter");

        jLabel3.setText("Enter Pipe Grade");

        jLabel4.setText("Pipe Colour(s)");

        jLabel5.setText("Pipe Insulation");

        jLabel6.setText("Pipe Reinforcement");

        jLabel7.setText("Quantity of Pipes");

        buttonGroup1.add(oneColour);
        oneColour.setText("1 Colour");
        oneColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneColourActionPerformed(evt);
            }
        });

        buttonGroup1.add(twoColours);
        twoColours.setText("2 Colours");

        buttonGroup1.add(noColours);
        noColours.setText("No Colours");

        buttonGroup2.add(insulationYes);
        insulationYes.setText("Yes");

        buttonGroup2.add(insulationNo);
        insulationNo.setText("No");

        buttonGroup3.add(reinforcementYes);
        reinforcementYes.setText("Yes");
        reinforcementYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinforcementYesActionPerformed(evt);
            }
        });

        buttonGroup3.add(reinforcementNo);
        reinforcementNo.setText("No");

        jLabel9.setText("Pipe Chemical Resistance");

        buttonGroup4.add(chemResistanceYes);
        chemResistanceYes.setText("Yes");
        chemResistanceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemResistanceYesActionPerformed(evt);
            }
        });

        buttonGroup4.add(chemResistanceNo);
        chemResistanceNo.setText("No");

        txtPipeSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPipeSizeActionPerformed(evt);
            }
        });

        txtPipeDiameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPipeDiameterActionPerformed(evt);
            }
        });

        butCalculate.setText("Calculate");
        butCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCalculateActionPerformed(evt);
            }
        });

        butAdd.setText("Add");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });

        buttonGroup5.add(pipeGrade1);
        pipeGrade1.setText("1");
        pipeGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeGrade1ActionPerformed(evt);
            }
        });

        buttonGroup5.add(pipeGrade2);
        pipeGrade2.setText("2");

        buttonGroup5.add(pipeGrade3);
        pipeGrade3.setText("3");

        buttonGroup5.add(pipeGrade4);
        pipeGrade4.setText("4");

        buttonGroup5.add(pipeGrade5);
        pipeGrade5.setText("5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPipeDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(pipeGrade1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pipeGrade2))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(reinforcementYes)
                                                .addComponent(insulationYes)
                                                .addComponent(chemResistanceYes))
                                            .addComponent(noColours))
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(reinforcementNo)
                                            .addComponent(insulationNo)
                                            .addComponent(chemResistanceNo)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(oneColour)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(pipeGrade3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(pipeGrade4)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pipeGrade5)
                                                    .addComponent(twoColours)))))
                                    .addComponent(txtPipeSize, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(83, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(butCalculate)
                                .addGap(18, 18, 18)
                                .addComponent(butAdd)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPipeSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPipeDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pipeGrade1)
                    .addComponent(pipeGrade3)
                    .addComponent(pipeGrade5)
                    .addComponent(pipeGrade2)
                    .addComponent(pipeGrade4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(noColours)
                    .addComponent(oneColour)
                    .addComponent(twoColours))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(insulationYes)
                    .addComponent(insulationNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(reinforcementYes)
                    .addComponent(reinforcementNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(chemResistanceYes)
                    .addComponent(chemResistanceNo))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCalculate)
                    .addComponent(butAdd))
                .addGap(37, 37, 37))
        );

        butExit.setText("Exit");
        butExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExitActionPerformed(evt);
            }
        });

        jLabel10.setText("Pipe Type: ");

        jLabel11.setText("Final Cost: ");

        txtPipeCost.setFocusable(false);
        txtPipeCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPipeCostActionPerformed(evt);
            }
        });

        txtPipeType.setFocusable(false);

        txtConsole.setColumns(20);
        txtConsole.setRows(5);
        txtConsole.setFocusable(false);
        jScrollPane1.setViewportView(txtConsole);

        jLabel12.setText("Pipe Cost:");

        jTextField1.setFocusable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPipeCost, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(txtPipeType)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butExit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPipeCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPipeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butExit)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(520, 735));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butExitActionPerformed

    private void oneColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneColourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneColourActionPerformed

    private void reinforcementYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinforcementYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reinforcementYesActionPerformed

    private void butCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCalculateActionPerformed
        if (pipeGrade1.isSelected() || pipeGrade2.isSelected() || pipeGrade3.isSelected()
                && noColours.isSelected() && insulationNo.isSelected() && reinforcementNo.isSelected()) {
            txtPipeType.setText("1");
        } else if (pipeGrade2.isSelected() || pipeGrade3.isSelected() || pipeGrade4.isSelected()
                && oneColour.isSelected() && insulationNo.isSelected() && reinforcementNo.isSelected()) {
            txtPipeType.setText("2");
        } else if (pipeGrade2.isSelected() || pipeGrade3.isSelected() || pipeGrade4.isSelected()
                || pipeGrade5.isSelected() && twoColours.isSelected() && insulationNo.isSelected()
                && reinforcementNo.isSelected()) {
            txtPipeType.setText("3");
        } else if (pipeGrade2.isSelected() || pipeGrade3.isSelected() || pipeGrade4.isSelected()
                || pipeGrade5.isSelected() && twoColours.isSelected() && insulationYes.isSelected()
                && reinforcementNo.isSelected()) {
            txtPipeType.setText("4");
        } else if (pipeGrade3.isSelected() || pipeGrade4.isSelected() || pipeGrade5.isSelected()
                && twoColours.isSelected() && insulationYes.isSelected() && reinforcementYes.isSelected()) {
            txtPipeType.setText("5");
        } else {
            txtConsole.setText("Invalid entry, no compatiable pipes found.");
        }
    }//GEN-LAST:event_butCalculateActionPerformed

    private void txtPipeCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPipeCostActionPerformed

    }//GEN-LAST:event_txtPipeCostActionPerformed

    private void txtPipeSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPipeSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPipeSizeActionPerformed

    private void txtPipeDiameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPipeDiameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPipeDiameterActionPerformed

    private void chemResistanceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemResistanceYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chemResistanceYesActionPerformed

    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
        txtPipeDiameter.setText("");
        txtQuantity.setText("");
        txtPipeSize.setText("");
        txtPipeType.setText("");
        txtPipeCost.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
    }//GEN-LAST:event_butAddActionPerformed

    private void pipeGrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeGrade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pipeGrade1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdd;
    private javax.swing.JButton butCalculate;
    private javax.swing.JButton butExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton chemResistanceNo;
    private javax.swing.JRadioButton chemResistanceYes;
    private javax.swing.JRadioButton insulationNo;
    private javax.swing.JRadioButton insulationYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton noColours;
    private javax.swing.JRadioButton oneColour;
    private javax.swing.JRadioButton pipeGrade1;
    private javax.swing.JRadioButton pipeGrade2;
    private javax.swing.JRadioButton pipeGrade3;
    private javax.swing.JRadioButton pipeGrade4;
    private javax.swing.JRadioButton pipeGrade5;
    private javax.swing.JRadioButton reinforcementNo;
    private javax.swing.JRadioButton reinforcementYes;
    private javax.swing.JRadioButton twoColours;
    private javax.swing.JTextArea txtConsole;
    private javax.swing.JTextField txtPipeCost;
    private javax.swing.JTextField txtPipeDiameter;
    private javax.swing.JTextField txtPipeSize;
    private javax.swing.JTextField txtPipeType;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
